"""empty message

Revision ID: 699a59f9d76a
Revises: 
Create Date: 2023-04-08 05:50:53.436924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699a59f9d76a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tx_age', sa.Integer(), nullable=True))
        batch_op.alter_column('geolocation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('unique_code')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('data_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.alter_column('geolocation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('tx_age')
        batch_op.drop_column('facility_id')

    # ### end Alembic commands ###
